### PR TITLE
Better error handling

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by toranb** [comment]
+100 !!!! nice work on this @williamsbdev

**Comment by williamsbdev** [comment]
@toranb would you do an npm publish? My internet connection keeps bombing in the middle or something.

**Comment by toranb** [comment]
On it boss - is the current (master) package.json /version good if I just pull and publish?

**Comment by toranb** [comment]
Looks like 0.2.0 is up - sorry for the slow reply (thought you might still be online)

**Comment by williamsbdev** [comment]
Thanks!

**Pull request merged**
